@HotelListingApi_HostAddress = http://localhost:5231

GET {{HotelListingApi_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{HotelListingApi_HostAddress}}/api/hotels/

###
GET {{HotelListingApi_HostAddress}}/api/Hotels/3